#' Assign deterministic filters and final confidence decisions to candidate burned patches
#'
#' @description
#' Assign deterministic confidence decisions to candidate burned patches
#' generated by the OtsuFire detection workflow.
#'
#' This function performs the deterministic scoring stage of the pipeline.
#' It receives candidate burned patches produced by
#' \code{\link[=detect_burned_patches]{detect_burned_patches()}} and
#' evaluates them through the canonical rule-based decision system used
#' by OtsuFire.
#'
#' The scoring workflow combines:
#' \enumerate{
#'   \item internal seed support and burnable-context plausibility
#'     (\strong{Filter 1}),
#'   \item optional active-fire hotspot corroboration
#'     (\strong{Filter 2}),
#'   \item temporal-consistency diagnostics against previous-year burned
#'     areas,
#'   \item spectral-support evaluation relative to a high-confidence
#'     burned-like reference distribution (\strong{Filter 3}).
#' }
#'
#' These components are then integrated into a final deterministic
#' confidence decision assigning each candidate patch to `keep`,
#' `review`, or `drop`.
#'
#' The function records the complete decision path of every candidate
#' patch, including filter outcomes, support metrics, temporal
#' diagnostics, and final decisions, producing a fully auditable
#' burned-area decision layer.
#'
#' Validation against an external burned reference is not performed by
#' this function. Users should subsequently evaluate outputs with
#' \code{\link[=validate_fire_maps]{validate_fire_maps()}} or other
#' downstream validation steps.
#'
#' @details
#' \strong{The two supported Filter-3 reference modes}
#'
#' Publicly, the package supports two ways of running \code{Filter 3}:
#'
#' \enumerate{
#'   \item \strong{Same year, local fallback (`keep_pool = NULL`).}
#'   The scoring engine builds the spectral reference internally from the
#'   same target year being scored. It uses the early internal keep core
#'   defined by \code{flag_internal == "keep"} after the seed-support and
#'   burnable-context screening. This is the native automatic baseline.
#'
#'   \item \strong{Other years, explicit keep pool.}
#'   The spectral reference is built outside the scorer from trusted
#'   decision layers belonging to other years. This is the cleanest
#'   explicit historical-reference mode.
#' }
#'
#' A same-year \emph{explicit} \code{keep_pool} is intentionally not a
#' supported public mode. It is methodologically circular and, when the
#' helper-generated metadata reveal that the explicit pool contains the
#' target year, the scorer rejects it and instructs the user to use
#' \code{keep_pool = NULL} instead.
#'
#' \strong{Rule-based deterministic scoring workflow}
#'
#' Candidate burned patches are evaluated through a sequential decision
#' system designed to distinguish high-confidence burned patches from
#' ambiguous or spurious detections while preserving full decision
#' traceability.
#'
#' \strong{Filter 1}
#'
#' Filter 1 is derived from the internal Stage-2 support screening and
#' burnable-context checks.
#'
#' Candidate patches intersecting Stage-1 support are assigned to the
#' \code{keep} pathway. Candidate patches without seed support are then
#' evaluated against the burnable domain:
#' \itemize{
#'   \item burnable but unseeded patches are assigned to \code{review},
#'   \item non-burnable patches are assigned to \code{drop},
#'   \item candidates with excessive missing vegetation / CORINE support
#'     may also be dropped.
#' }
#'
#' Filter 1 is recorded through \code{filter_1} and \code{reason_1}.
#'
#' \strong{Filter 2}
#'
#' Filter 2 evaluates external corroboration using active-fire hotspots
#' when hotspot data are available for the target year.
#'
#' In the current public implementation:
#' \itemize{
#'   \item hotspot-supported patches are mapped to `filter_2 = "keep"`,
#'   \item hotspot-free patches are mapped to `filter_2 = "review"`,
#'   \item when hotspot data are unavailable, Filter 2 is recorded as not
#'     applied.
#' }
#'
#' Filter 2 is recorded through \code{filter_2} and \code{reason_2}.
#'
#' \strong{Temporal consistency assessment}
#'
#' Temporal consistency is evaluated separately from Filters 1 to 3.
#' Overlap with previous-year burned areas is used to diagnose residual
#' old scars, repeated detections, or temporal conflicts.
#'
#' These diagnostics are recorded through:
#' \itemize{
#'   \item `preyear_overlap_frac`
#'   \item `preyear_action`
#'   \item `preyear_reason`
#' }
#'
#' In the current canonical public implementation, this temporal branch
#' is preserved as an auditable companion diagnostic. The final public
#' field \code{class_final} is derived canonically from Filters 1, 2, and
#' 3.
#'
#' \strong{Filter 3}
#'
#' Filter 3 evaluates spectral consistency relative to a high-confidence
#' keep-support distribution.
#'
#' The workflow computes patch-level metrics such as:
#' \itemize{
#'   \item \code{percentile_in_keep}
#'   \item \code{p_above_keep_ref}
#'   \item \code{p_above_keep_q25}
#'   \item \code{area_ha}
#'   \item \code{n_pix}
#'   \item \code{conf_area}
#'   \item \code{conf_pix}
#' }
#'
#' Patches are promoted to the spectral \code{keep} pathway only when
#' they satisfy the configured percentile and exceedance thresholds and
#' also pass the minimum area and minimum pixel checks.
#'
#' In the current public implementation:
#' \itemize{
#'   \item spectrally well-supported patches become `filter_3 = "keep"`,
#'   \item borderline or weakly supported patches typically become
#'     `filter_3 = "review"`,
#'   \item `filter_3 = "drop"` is mainly reserved for failures of minimum
#'     geometric support such as `conf_area == "too_small"` or
#'     `conf_pix == "too_few_pix"`.
#' }
#'
#' Filter 3 is recorded through \code{filter_3} and \code{reason_3}.
#'
#' \strong{How the burned-like support reference is defined}
#'
#' Spectral support in Filter 3 is always evaluated relative to a
#' keep-like reference distribution.
#'
#' \strong{Local same-year fallback}
#'
#' When `keep_pool = NULL`, the scoring engine derives that reference
#' internally from the same target year being scored.
#'
#' More precisely, the local reference is built from the internal
#' same-year keep core defined by:
#' \itemize{
#'   \item candidate polygons entering the Stage-2 keep/review layer,
#'   \item restricted to polygons with `flag_internal == "keep"`.
#' }
#'
#' This means the local same-year reference is based on the
#' seed-supported internal keep core of the target year. It is \emph{not}
#' derived from:
#' \itemize{
#'   \item final `class_final == "keep"` polygons,
#'   \item an external burned registry,
#'   \item or an externally validated burned map for that same year.
#' }
#'
#' From this same-year keep core, the engine extracts finite
#' change-index pixel values and derives:
#' \itemize{
#'   \item `qref_keep`
#'   \item `q25_keep`
#'   \item `keep_medians`
#'   \item the empirical support distribution used for
#'     `percentile_in_keep`.
#' }
#'
#' \strong{Explicit reference built from trusted external decision layers}
#'
#' When `keep_pool` is supplied, Filter 3 uses that explicit external
#' reference directly and does not rebuild the local same-year fallback.
#'
#' This explicit pool can be built from one or multiple trusted decision
#' layers, typically using:
#' \itemize{
#'   \item \code{\link[=collect_keep_reference_samples]{collect_keep_reference_samples()}}
#'   \item \code{\link[=build_keep_pool_from_samples]{build_keep_pool_from_samples()}}
#' }
#'
#' In the current helper workflow, historical samples are selected using
#' a strict rule requiring:
#' \itemize{
#'   \item `class_final == "keep"`
#'   \item `filter_1 == "keep"`
#'   \item `filter_2 == "keep"`
#'   \item `filter_3 == "keep"`
#'   \item `conf_area == "ok"`
#'   \item `conf_pix == "ok"`
#'   \item minimum area compliance
#'   \item and no temporal drop when `preyear_action` is available.
#' }
#'
#' This makes the explicit historical \code{keep_pool} stricter and more
#' externally controlled than the internal same-year fallback.
#'
#' Helper-generated explicit pools retain \code{metadata$years_used}. If
#' those years include the current \code{target_year}, the public scorer
#' rejects the pool as an unsupported same-year explicit reference. In
#' that case, use \code{keep_pool = NULL} for the native same-year local
#' fallback.
#'
#' \strong{Final deterministic integration}
#'
#' The outputs of Filters 1, 2, and 3 are integrated into a final
#' deterministic confidence decision recorded in \code{class_final}.
#'
#' In broad terms:
#' \itemize{
#'   \item fully consistent support leads to `keep`,
#'   \item mixed or unresolved evidence leads to `review`,
#'   \item strong contextual rejection leads to `drop`.
#' }
#'
#' In the current canonical implementation, if exactly one active filter
#' drops a polygon but the remaining active filters keep it, the final
#' decision is softened to `review` rather than `drop`.
#'
#' @param burned_candidates sf POLYGON, SpatVector, or path to a readable
#'   vector file. Candidate burned patches generated by
#'   \code{\link[=detect_burned_patches]{detect_burned_patches()}} after
#'   seed-and-grow segmentation and refinement.
#' @param config An `otsufire_burned_mapping_config` object returned by
#'   \code{\link[=build_burned_mapping_config]{build_burned_mapping_config()}}.
#'   The configuration controls methodological thresholds, temporal
#'   cleanup behaviour, support buffers, and scoring logic.
#' @param keep_pool Optional explicit keep-like reference pool used for
#'   spectral-support scoring in \code{Filter 3}. This should be a
#'   pre-built keep-pool summary object matching the contract consumed by
#'   \code{\link[=score_rbr_keep_classes]{score_rbr_keep_classes()}}, for
#'   example the object returned by
#'   \code{\link[=build_keep_pool_from_samples]{build_keep_pool_from_samples()}}.
#'
#'   In very simple language:
#'   \itemize{
#'     \item `keep_pool = NULL` means: "use the same year, automatically,
#'       from the early internal keep core";
#'     \item `keep_pool = <explicit pool from other years>` means: "score
#'       this year against a burned-like reference learned from trusted
#'       external years".
#'   }
#'
#'   When supplied, the scoring workflow uses this reference directly.
#'   Explicit pools built from the same target year are intentionally not
#'   a supported public mode; use `keep_pool = NULL` for same-year
#'   scoring.
#'   For backward compatibility, a legacy wrapper of the form
#'   \code{list(keep_pool = <summary>)} is also accepted and unwrapped
#'   internally.
#'
#'   Deterministic scoring does not read or depend on external
#'   burned-like registries: support resolution is strictly explicit
#'   \code{keep_pool} or local fallback.
#' @param write_outputs Logical scalar. Whether scoring products should be
#'   written to disk. Default `TRUE`.
#' @param overwrite Logical scalar. Whether existing scoring outputs may
#'   be replaced. Default `FALSE`.
#'
#' @return A named list with fields:
#' \describe{
#'   \item{`internal_decisions`}{Canonical deterministic decision layer
#'     with full filter outcomes, support metrics, temporal-overlap
#'     diagnostics, and final decisions.}
#'   \item{`internal_decisions_path`}{Path to the written internal
#'     decision layer.}
#'   \item{`reference_decisions`}{Reference-side deterministic decision
#'     layer, when available.}
#'   \item{`reference_decisions_path`}{Path to the written reference
#'     decision layer, when available.}
#'   \item{`keep_pool_summary`}{Summary object describing the keep-like
#'     spectral-support reference distribution used during scoring.}
#'   \item{`scoring_diagnostics`}{Auxiliary diagnostics and scoring
#'     metadata generated during deterministic filtering.}
#' }
#'
#' @seealso
#' \code{\link[=build_burned_mapping_config]{build_burned_mapping_config()}},
#' \code{\link[=detect_burned_patches]{detect_burned_patches()}},
#' \code{\link[=run_deterministic_pipeline]{run_deterministic_pipeline()}},
#' \code{\link[=validate_fire_maps]{validate_fire_maps()}},
#' \code{\link[=collect_keep_reference_samples]{collect_keep_reference_samples()}},
#' \code{\link[=build_keep_pool_from_samples]{build_keep_pool_from_samples()}}
#' @export
score_burned_patches <- function(burned_candidates, config, keep_pool = NULL,
                                 write_outputs = TRUE, overwrite = FALSE) {

  if (!inherits(config, "otsufire_burned_mapping_config")) {
    stop("'config' must be created by build_burned_mapping_config().",
         call. = FALSE)
  }
  if (!is.logical(write_outputs) || length(write_outputs) != 1L) {
    stop("'write_outputs' must be TRUE or FALSE.", call. = FALSE)
  }
  if (!is.logical(overwrite) || length(overwrite) != 1L) {
    stop("'overwrite' must be TRUE or FALSE.", call. = FALSE)
  }

  if (missing(burned_candidates) || is.null(burned_candidates)) {
    stop("'burned_candidates' is required.", call. = FALSE)
  }

  # Validate config content (change_index) before touching burned_candidates
  # on disk — if the config itself is not usable, we fail fast with a
  # config-level error instead of a misleading path-existence error.
  if (is.null(config$inputs$change_index)) {
    stop(
      "score_burned_patches(): config$inputs$change_index is NULL.\n",
      "Rebuild the config with an explicit 'change_index' argument.",
      call. = FALSE
    )
  }
  .of_check_input_file(config$inputs$change_index, "change_index")

  if (is.character(burned_candidates) && length(burned_candidates) == 1L) {
    if (!file.exists(burned_candidates)) {
      stop("'burned_candidates' path does not exist: ", burned_candidates,
           call. = FALSE)
    }
  } else if (!inherits(burned_candidates, c("sf", "SpatVector"))) {
    stop(
      "'burned_candidates' must be an sf POLYGON, SpatVector, or a readable path.",
      call. = FALSE
    )
  }

  keep_pool <- .of_normalize_keep_pool_arg(keep_pool)
  keep_pool <- .of_validate_keep_pool_target_year(
    keep_pool,
    config$target_year
  )

  res <- .of_run_scoring(burned_candidates, config, keep_pool = keep_pool,
                         write_outputs = isTRUE(write_outputs),
                         overwrite = isTRUE(overwrite))

  list(
    internal_decisions       = res$internal_decisions,
    internal_decisions_path  = res$internal_decisions_path %||% NA_character_,
    reference_decisions      = res$reference_decisions,
    reference_decisions_path = res$reference_decisions_path %||% NA_character_,
    keep_pool_summary        = res$keep_pool_summary,
    scoring_diagnostics      = res$scoring_diagnostics
  )
}
